### ISSUE TITLE
Jfrontend: only images in resources folder are set as background

### ISSUE THREAD

**Issue by mcicolella** [freedomotic/freedomotic#117]
When you try to set a new background image the system proposes "resources" folder to make your choice.
You can move to any other folder on your system, outside of Freedomotic installation, but in this case the background is not set and only a log message is reported.
Possible solutions
1. disable UpFolderButton in GUI
2. notify user with a visual message when the image is not set
3. other ... 

Ref. https://github.com/freedomotic/freedomotic/blob/master/plugins/devices/frontend-java/src/main/java/com/freedomotic/jfrontend/MainWindow.java (method mnuBackgroundActionPerformed (java.awt.event.ActionEvent evt))

**Comment by mcicolella** [comment]
@P3trur0 what do you think?

**Comment by P3trur0** [comment]
Hi @mcicolella I'd go with the easiest approach, I mean by disabling the UpFolderButton in GUI.

Btw, if you agree I'd like to pick this.
