### ISSUE TITLE
Create wiki page for P2P config and scenarios

### ISSUE THREAD

**Issue by bestmazzo** [freedomotic/freedomotic#120]
Since P2P is a one of our 'jewel of the crown' we should explain its usage (scenarios and related config) in a dedicated page.
This would help people better understand its power and deploy the best solution of their aims.

**Comment by mcicolella** [comment]
We have already a draft https://github.com/freedomotic/freedomotic/wiki/P2P we could extend with more details as you said.

**Comment by bestmazzo** [comment]
And we could even link it on the sidebar menu (in a dedicate section "configuration" ?). Just a proposal.

**Comment by mcicolella** [comment]
I'm closing this issue. All the documentation is hosted on http://freedomotic-user-manual.readthedocs.io/en/latest/advanced-features/p2p.html
