### ISSUE TITLE
Finetune log mechanism to improve user's feedback analysis

### ISSUE THREAD

**Issue by mcicolella** [freedomotic/freedomotic#125]
There are two mayor aspects about that: 
a) log starts at an advanced  [boot stadium](https://github.com/freedomotic/freedomotic/blob/master/framework/freedomotic-core/src/main/java/com/freedomotic/app/Freedomotic.java#L233) so if something happens at early startup the only way of getting information is looking at console messages
b) log should be easily appended to issue reports

Some tips for log system 
http://www.setfirelabs.com/freedomotic/freedomotic-logging-for-development-and-debugging
http://www.setfirelabs.com/freedomotic/freedomotic-logging-for-development-and-debugging-part-2

**Comment by mcicolella** [comment]
@P3trur0 What about this? Do you think we could use your solution for mailer to attach logs? We are thinking about a simple way to make simple for users to report issues.

**Comment by P3trur0** [comment]
@mcicolella my fix basically works as follow:

1. it enhances Mailer plugin to support the sending of attachments, if any;
2. it introduces an attachmentPath property to `MessageEvent` payload.

As far as I understand the code, Mailer class listens to either Commands or [Events](https://github.com/freedomotic/freedomotic/blob/master/plugins/devices/mailer/src/main/java/com/freedomotic/plugins/devices/mailer/Mailer.java#L138). So, if in the scope of Logs you have chance to trigger `MessageEvent` instances, then you could set an attachmentPath (either an [absolute String path](https://github.com/P3trur0/freedomotic/blob/4082d57baa299a10ad5abb9c718c8d3970684ea6/framework/freedomotic-core/src/main/java/com/freedomotic/events/MessageEvent.java#L117) or a [File](https://github.com/P3trur0/freedomotic/blob/4082d57baa299a10ad5abb9c718c8d3970684ea6/framework/freedomotic-core/src/main/java/com/freedomotic/events/MessageEvent.java#L128) reference) referring to the log file you like to send, then it should go with mail sending together with attachments.

Please, let me know if you need any other information or more help. I'd be glad to work on it.

---

P.s.: About the log boot stadium, instead: what if [here](https://github.com/freedomotic/freedomotic/blob/master/framework/freedomotic-core/src/main/java/com/freedomotic/app/Freedomotic.java#L233) the config object is not yet instantiated? It seems NPE prone.
I'd go the other way around:

```java
!"OFF".equalsIgnoreCase(config.getStringProperty("KEY_SAVE_LOG_TO_FILE", "OFF").trim())
```

**Comment by mcicolella** [comment]
@P3trur0 First of all thanks for your support! It's a pleasure to discuss with you and share our opinions.
We can send commands programmatically (as in this sample https://github.com/freedomotic/freedomotic/wiki/Natural-language-processing)
Now in Jfrontend (java GUI for FD) we have a menu item ["Report an issue"](https://github.com/freedomotic/freedomotic/blob/a4967cd33bb4ba967d9c7ba20304f084fc166b34/plugins/devices/frontend-java/src/main/java/com/freedomotic/jfrontend/MainWindow.java#L1377)  pointing to an external Google form.
My idea is to create a command to send a message to a predefined FD mail with the attached logs via Mailer plugin.
Two points:
- the system should check if log is enabled (https://github.com/freedomotic/freedomotic/wiki/Logging)
- the system should check if Mailer plugin is installed and active (this could be avoided by packaging the Mailer in the release package)
and show a specific message is necessary

**Comment by P3trur0** [comment]
@mcicolella you're welcome, my pleasure indeed.
About this issue I guess it is feasible. If you please I can give it a try next weekend.

**Comment by P3trur0** [comment]
Hi @mcicolella I am developing this requirement.

The skeleton of the `MainWindow` behavior has been properly set up; the idea is to display an option dialog when the user clicks on the "Report an issue" menu item.

The above mentioned Option Dialog will offer two options to the user:

- Compile an external Google Form describing the issue;
- Send the logs (by Mailer plugin behind the scenes);

Like this 

![one](http://i.imgur.com/4MPMusw.png)

However I am stuck on a problem [here](https://github.com/P3trur0/freedomotic/blob/issue_125/plugins/devices/frontend-java/src/main/java/com/freedomotic/jfrontend/MainWindow.java#L1397).

Basically:

1. I don't know how to detect if the Mailer plugin is currently installed;
 
2. I don't know how to access Freedomotic instance variables without using its static methods (as you can see [here](https://github.com/P3trur0/freedomotic/blob/issue_125/framework/freedomotic-core/src/main/java/com/freedomotic/app/Freedomotic.java#L440) I've created an utility method to enable the log to file feature. This method returns `true` if the _log to file_ has been enabled so this value could be set to the Freedomotic instance variables to track if the _log to file_ has been enabled).

Any help?

Hope my doubts are clear, otherwise I'll be glad to explain them better!

Thank you!

**Comment by mcicolella** [comment]
Hi @P3trur0 great work!

1. We have some API so you can get a list of plugins with api.getClients("plugin"). Please refer to [this](https://github.com/freedomotic/freedomotic/blob/master/plugins/devices/restapi-v3/src/main/java/com/freedomotic/plugins/devices/restapiv3/resources/jersey/PluginResource.java) and [this](https://github.com/freedomotic/freedomotic/blob/master/framework/freedomotic-core/src/main/java/com/freedomotic/api/APIStandardImpl.java)
Anyway I'm thinking of including Mailer in the package as an "essential" plugin. 

2. To enable log to file we use a property in the config.xml file (https://github.com/freedomotic/freedomotic/wiki/Logging). It's managed in https://github.com/freedomotic/freedomotic/blob/master/framework/freedomotic-core/src/main/java/com/freedomotic/app/Freedomotic.java. Is it ok for your aim?

Thank you!

PD: if you have any suggestion to improve the system or fix a problem please open a specific issue so we can discuss about it.

**Comment by P3trur0** [comment]
Hi @mcicolella, thank you for your explanation!

About point n.1 yes, your explanation is definitely clear. 
I'll go with that approach to verify if the `Mailer` plugin is properly running (by the way, is its identification name `"mailer"`?)

About n.2 instead, my question was something like:  
how can I understand, in `MainWindow`, if the current `Freedomotic` instance has _log to file_ enabled?

My idea was to offer a method in `Freedomotic` class, returning a boolean.
However it seems that Freedomotic offers just `static` methods. Do I have to go with a static one, then?
(I would use the result of [this call](https://github.com/P3trur0/freedomotic/blob/issue_125/framework/freedomotic-core/src/main/java/com/freedomotic/app/Freedomotic.java#L359) to let Freedomotic know if the log has been enabled to go on files.). 

For example in `MainWindow` we could say (pseudocode hereby):

```java
if(Freedomotic.hasLogToFile()) {
    //TODO here goes the actual log file retrieval and sending
} else {
 //TODO here do not send any e-mail because no log to file has been enabled
}
```

Finally, where could I get the **FREEDOMOTIC_ROOT** value? Is it stored somewhere?

Thank you again!

**Comment by mcicolella** [comment]
Hi @P3trur0 

1. "Mailer" is the plugin name
2. Your method for checking if the log is enabled seems good. Consider it as "static". As reported in point a) of the issue the log misses some messages as you can see by starting Freedomotic from command line. Any idea?  
3. FREEDOMOTIC_ROOT corresponds to the installation folder. You can find all "paths" in https://github.com/freedomotic/freedomotic/blob/master/framework/freedomotic-core/src/main/java/com/freedomotic/settings/Info.java

Thanks

**Comment by P3trur0** [comment]
@mcicolella,

[PR is on its way](https://github.com/freedomotic/freedomotic/pull/228)! :)

Good evening,
@P3trur0

**Comment by mcicolella** [comment]
Hi @P3trur0 
great work! I'll integrate it ASAP. 
Thanks

PD: I'll ask your opinion about other topics
