### ISSUE TITLE
Authc: secure passwords into privileges file

### ISSUE THREAD

**Issue by mcicolella** [freedomotic/freedomotic#132]
Users' password is now kept in plaintext into privileges.conf file.
We should store them in an encrypted way.

**Comment by dmitraver** [comment]
Hi!

I would like to help with that. What options do you consider here? I'm not really into the project so can you please elaborate why the passwords are stored in a plaintext?

**Comment by dmitraver** [comment]
@mcicolella I went quickly through the code and found a predefined credentials for the admin user in a plaintext. There is no way to create new users as far as I can tell. Do you actually want to store admin credentials in a secure way?

**Comment by bestmazzo** [comment]
@dmitraver Thank you for your proposal. Currently passwords are stored in plaintext as we found it easier to debug when we introduced the authentication layer. Now we could consider it stable enough to store passwords securely. 

A few more information:
- as you may have noticed, we use Shiro framework for authentication and authorization 
- in theory, securing passwords should require a few code changes in https://github.com/freedomotic/freedomotic/blob/master/framework/freedomotic-core/src/main/java/com/freedomotic/security/UserRealm.java
- https://shiro.apache.org/realm.html could be a good start

Should you need any help, just quote me, I'll get to you asap.

Matteo

**Comment by dmitraver** [comment]
@bestmazzo Thank you for clarification. I will make a PR soon. I also made one PR that fixes an exception that is thrown by activemq during application shutdown so please take a look once you have time ;)
