### ISSUE TITLE
HttpHelper: add method for http post request

### ISSUE THREAD

**Issue by mcicolella** [freedomotic/freedomotic#163]
[HttpHelper](https://github.com/freedomotic/freedomotic/blob/master/framework/freedomotic-core/src/main/java/com/freedomotic/helpers/HttpHelper.java) supports only GET requests. We should add a method for POST requests.

**Comment by nitram509** [comment]
What's the use case?
Who uses it?

**Comment by mcicolella** [comment]
@nitram509 thanks for your answer. For example you could use a POST request in a plugin to publish on a cloud platform as ThingSpeak. Anyway the idea is to make the helper as general as possible with all the options for users.

**Comment by bhdrkn** [comment]
Starting working on this. But this helper creating HttpClient for each request. It is not a good way to use, but i will keep it as it is. You may want to consider creating a refactoring issue.

**Comment by mcicolella** [comment]
There is already a pull request for this issue. Please check and verify it for any integration. Thanks

**Comment by bhdrkn** [comment]
@mcicolella thanks for heads up. I checked the pull request and it does not contain post method.  @nitram509 if you are not going to implement this, I am willing to do it. Please let me know.

**Comment by nitram509** [comment]
@bhdrkn Feel free to go ahead with implementing POST.

To be honest, I don't see that much value in implementing a helper function, without any concrete need.
Please don't get me wrong here. I'm not against such helper functions in general, but without any concrete use case or scenario I simply don't know, how the method should look like and what are its responsibilities.

Regards
Martin

**Comment by mcicolella** [comment]
@nitram509 @bhdrkn We have some plugins to control domotic boards with an embedded webserver. Commands are sent as HTTP requests and the status (e.g. relais ON/OFF) is checked by parsing an XML file. Many times the webserver requires authentication. 
The helper makes simpler to manage this tasks.
