### ISSUE TITLE
Remove .xenv file when an environment is deleted

### ISSUE THREAD

**Issue by mcicolella** [freedomotic/freedomotic#177]
Now when an environment is deleted its .xenv file remains.
It'd be removed. In particular we'd prevent the default env (set in KEY_ROOM_XML_PATH property) can deleted.
This check is done in jfrontend (if we have only an environment "Delete" option is disabled) but not in API where any environment can be removed.

**Comment by P3trur0** [comment]
@mcicolella if I properly understand here the requirement is to remove the `.xenv` file each time an environment is deleted both from Jfrontend and APIs.

In which Java class can I find the environment removal operation?

**Comment by P3trur0** [comment]
@mcicolella what about deleteAll method? Should in this case the default enviroment be removed?

**Comment by mcicolella** [comment]
@P3trur0 I think that the default environment shouldn't removed anyway. IMHO it's an integrity constraint.

**Comment by P3trur0** [comment]
@mcicolella ok then, so deleteAll, despite its actual name will delete all but the default one. Is this ok?

**Comment by P3trur0** [comment]
@mcicolella are you sure that `KEY_ROOM_XML_PATH` does contain the reference to default environment? It seems containing a reference to the folder, not to the default environment.

**Comment by mcicolella** [comment]
@P3trur0 it points to the default .xenv file

**Comment by P3trur0** [comment]
@mcicolella please see [this PR](https://github.com/freedomotic/freedomotic/pull/251), I guess it resolves the problem.

**Comment by mcicolella** [comment]
Integrated! Thanks
