### ISSUE TITLE
Add a translation for your language

### ISSUE THREAD

**Issue by mcicolella** [freedomotic/freedomotic#189]
Freedomotic supports more than 20 languages using Transifex.
We are searching contributors for new languages or existing translations.

1. Solution (recommanded in particular for new language)
- Join our team on Transifex (https://www.transifex.com/freedomotic/freedomotic-open-source-buildi/)
- Complete the translation
- Download the file .properties and submit a PR

2. Solution
Work directly on the files in https://github.com/freedomotic/freedomotic/tree/master/framework/freedomotic-core/i18n
and https://github.com/freedomotic/freedomotic/tree/master/plugins/devices/frontend-java/src/main/resources/data/i18n and submit a PR

If you want to apply please add a comment here so we can open a specific issue and track
the tasks.

**Comment by amitkumarj441** [comment]
Hey @mcicolella,

I'm willing to take up this task and I would like to translate [Freedomotic](https://www.transifex.com/freedomotic/freedomotic-open-source-buildi/) in our local langiage. Please add "Hindi"(Hi) language on transifex, so that I can able to finish this task asap.

Cheers,
Amit Kumar Jaiswal

**Comment by mcicolella** [comment]
@amitkumarj441 Just added Hindi language. I'm opening a specific issue for this so you can reference it in your PR. Thanks for support

**Comment by mcicolella** [comment]
@theomessin In https://github.com/freedomotic/freedomotic/blob/master/plugins/devices/frontend-java/src/main/resources/data/i18n/jfrontend_el_GR.properties there are some strings not translated in Greek. Can you work on it? 
Thanks

**Comment by JingMa87** [comment]
I can translate to Dutch! ;)

**Comment by Sacret** [comment]
I see there are some inaccuracies in Russian translation. I can check and fix them

**Comment by mcicolella** [comment]
@Sacret Thanks. If you want you can join the Transifex Russian team.

**Comment by Sacret** [comment]
@mcicolella I applied to the team but got this: `You were not accepted to be part of the team Freedomotic Open Source Building Automation team for Russian (Russia).`

**Comment by mcicolella** [comment]
@Sacret What's your nickname on Transifex? I don't see any request for joining

**Comment by Sacret** [comment]
@mcicolella I have the same username as here: `sacret`

**Comment by mcicolella** [comment]
@Sacret Just added. Can you confirm?

**Comment by JuanRodriguez32** [comment]
I can translate it to Spanish. Let me know if you need it!

**Comment by brittat** [comment]
I would be happy to provide a Swedish translation if you need one!

**Comment by rodrigo-brito** [comment]
I can translate to Portuguese-BR

**Comment by yacdaniel** [comment]
I can translate to Spanish.

**Comment by mcicolella** [comment]
@brittat If you want you can join our team on Transifex. We have a partial Swedish translation https://www.transifex.com/freedomotic/freedomotic-open-source-buildi/language/sv_SE/

**Comment by mcicolella** [comment]
@rodrigo-brito Portuguese-BR translation is almost complete.
We must translate only 3 strings:

- ROOM/ZONE SELECTED
- Really delete room {0}?
- Delete room

**Comment by rodrigo-brito** [comment]
Ok, I send a request in transifex.

**Comment by rodrigo-brito** [comment]
@mcicolella Where are these strings?

**Comment by mcicolella** [comment]
@rodrigo-brito In Jfrontend resource (Transifex) or https://github.com/freedomotic/freedomotic/blob/master/plugins/devices/frontend-java/src/main/resources/data/i18n/jfrontend_pt_BR.properties

**Comment by MilindaLaknath** [comment]
Hi @mcicolella,

I'm Milinda and I can translate it into [Sinhala](https://en.wikipedia.org/wiki/Sinhalese_language).
I like to contribute. Join me in.

Thank you.
Milinda

**Comment by rodrigo-brito** [comment]
@mcicolella Thank you!

**Comment by mcicolella** [comment]
@MilindaLaknath Thanks for your proposal! You can join our Transifex team and make a request for your language.

**Comment by mjurinic** [comment]
Hey @mcicolella, I've sent you a request for Croatian on Transifex :)

**Comment by mcicolella** [comment]
@mjurinic I can't see your request on Transifex.

**Comment by mcicolella** [comment]
@brittat are you still interested in translating in Swedish?

**Comment by bureken** [comment]
I'd like to complete Turkish translation. I requested to join the them at transifex and waiting confirmation.

**Comment by wolframtheta** [comment]
I can translate it to Catalan :)

**Comment by rodrigo-brito** [comment]
We have the Catalan(Spain) trasnlation @wolframtheta,you can translate for other country or suggest corrections too.

**Comment by wolframtheta** [comment]
I did not see the language the list...

**Comment by rodrigo-brito** [comment]
Sorry @wolframtheta, I comment in the wrong issue.

**Comment by wolframtheta** [comment]
Then, I can do it? I sent you the request on the page

**Comment by pvtuan10** [comment]
I will finish the existing Vietnamese translation.

**Comment by eternalBlast** [comment]
I will finish the Indonesian translation

**Comment by mcicolella** [comment]
I'm closing this issue. 
Thank you for your support
