### ISSUE TITLE
Add translations for Hindi

### ISSUE THREAD

**Issue by mcicolella** [freedomotic/freedomotic#191]

**Comment by amitkumarj441** [comment]
Thanks @mcicolella for creating this issue! I'll soon initiate a PR for this language.

**Comment by rohanagarwal94** [comment]
@mcicolella shall I work on this since the PR has not been generated yet?

**Comment by mcicolella** [comment]
@rohanagarwal94 Of course if you want! We have already a resource for this language on Transifex https://www.transifex.com/freedomotic/freedomotic-open-source-buildi/language/hi_IN/

**Comment by rohanagarwal94** [comment]
@mcicolella please merge my PR.
