### ISSUE TITLE
Develop a mobile client 

### ISSUE THREAD

**Issue by mcicolella** [freedomotic/freedomotic#208]
#We have already a first prototype of Android client (https://github.com/freedomotic/fd-android-client) but it's not updated.
In the meantime we developed a new and complete RESTful API (demo http://localhost9111/ admin/admin as credentials).
We'd like to create a mobile app (maybe an hybrid one based on Cordova for code reuse on different platforms) to interact with our framework.

**Comment by Tchinmai7** [comment]
I can work on this. Native Android. Let me know what are the expected features.

**Comment by mcicolella** [comment]
Hi 
as first stage we'd like 
- to login
- to select an environment, the list of rooms in it and the things 
- for each thing to view its properties (aka behaviors) and send commands (e.g.  turn on, off)
- to list all installed plugins and start/stop it
- to list users 
Thanks

**Comment by mcicolella** [comment]
@Tchinmai7 we can add multilanguage support

**Comment by mcicolella** [comment]
We can use https://marvelapp.com/ for prototyping

**Comment by mcicolella** [comment]
@Tchinmai7 Still interested?

**Comment by Tchinmai7** [comment]
Sorry, was busy last month. can start next week or so

**Comment by gappsil** [comment]
How can we get more details..?
