### ISSUE TITLE
Some improvements to MQTT client plugin

### ISSUE THREAD

**Issue by mcicolella** [freedomotic/freedomotic#209]
The current plugin version (https://github.com/freedomotic/freedomotic/tree/master/plugins/devices/mqtt-client) subscribes only a single topic as reported in the manifest.xml file (https://github.com/freedomotic/freedomotic/blob/master/plugins/devices/mqtt-client/src/main/resources/mqtt-client-manifest.xml)

- We should extend it to subscribe more topics by reading them from a tuple block in the manifest file as in the example https://github.com/freedomotic/freedomotic/blob/master/plugins/devices/mysensors/src/main/resources/mysensors-manifest.xml

- The messageArrived() method in https://github.com/freedomotic/freedomotic/blob/master/plugins/devices/mqtt-client/src/main/java/com/freedomotic/plugins/devices/mqttclient/Mqtt.java should be modified to send as "address" the complete topic (removing rows 121-123)

- All System.out.println() instructions would be converted to log messages

**Comment by atanasg** [comment]
I would start with the System.out.println() part
