### ISSUE TITLE
MaryTTS plugin: convert log messages to Slf4j

### ISSUE THREAD

**Issue by mcicolella** [freedomotic/freedomotic#211]
We should convert all log messages to Slf4j in https://github.com/freedomotic/freedomotic/blob/master/plugins/devices/marytts/src/main/java/com/freedomotic/plugins/marytts/MaryTTS.java

Ref. example https://github.com/freedomotic/freedomotic/blob/master/plugins/devices/ipcamera-motion/src/main/java/com/freedomotic/plugins/devices/ipcameramotion/IpCameraMotion.java

**Comment by ArkantosC** [comment]
Hi @mcicolella. I can help you with this one.
