### ISSUE TITLE
Mailer plugin: add support for attachments

### ISSUE THREAD

**Issue by mcicolella** [freedomotic/freedomotic#217]
Our Mailer plugin can send notifications by mail when an event occurs (eg. an object is clicked) but it doesn't manage attachments.
It'd be useful to find a way to do this: for example sending a picture taken from the camera when motion detected (plugin https://github.com/freedomotic/freedomotic/tree/master/plugins/devices/ipcamera-motion)

Plugin doc: http://freedomotic.com/content/plugins/mailer
Plugin code:https://github.com/freedomotic/freedomotic/blob/master/plugins/devices/mailer/src/main/java/com/freedomotic/plugins/devices/mailer/Mailer.java

**Comment by P3trur0** [comment]
Hi @mcicolella I can go with this, if you please.

**Comment by mcicolella** [comment]
@P3trur0 OK!

**Comment by P3trur0** [comment]
#218 this should help in add attachment to e-mails.
