### ISSUE TITLE
IpCamera motion plugin: save last captured image with a specific name

### ISSUE THREAD

**Issue by mcicolella** [freedomotic/freedomotic#219]
Now when motion is detected the plugin saves an image in the format "camera_name-date.jpg".
In order to attach the image to an email using Mailer plugin we have to specify the file name in the command (as a fixed absolute path). Every captured image has a different name so it's difficult to do this.
The idea is to save the image also as "camera_name-latest.jpg". This file is replaced by every new captured image but the old are anyway saved.

Any suggestion??

Ref. code https://github.com/freedomotic/freedomotic/blob/master/plugins/devices/ipcamera-motion/src/main/java/com/freedomotic/plugins/devices/ipcameramotion/IpCameraMotion.java

**Comment by rrishabhj** [comment]
how about saving the name in a shared preference.

**Comment by mcicolella** [comment]
@rrishabhj What do you mean exactly?

**Comment by mcicolella** [comment]
With the last changes to the mailer plugin we could send a MessageEvent to the mailer with the path of the last captured image.

**Comment by mcicolella** [comment]
An example to test is [here](https://github.com/mcicolella/freedomotic/commit/9d1c2aa4ac4e52a63f0d8499fa11fb7d9de675ef)

**Comment by P3trur0** [comment]
@mcicolella 

what about to compress all the images captured so far in a zip file and attach this single zip to the e-mail?

**Comment by mcicolella** [comment]
@P3trur0 Good point! 
But in this case when would be sent the zipped file?
I'm trying to explain: now when motion is detected an event is notified and a picture captured. So an user can receive an email or a telegram notification reporting a possible intrusion. This is in realtime so he can react immediately.
If motion is no more detected there are not other notified events. So how to determine when sending the images?
Hope it's clear

**Comment by P3trur0** [comment]
@mcicolella ok then, I see your [example](https://github.com/mcicolella/freedomotic/commit/9d1c2aa4ac4e52a63f0d8499fa11fb7d9de675ef#diff-4148f89428b512b8424a1700010eae4bR260). It seems good, indeed in this way you can send an image for each motion detected (named `camera_name-<DATE>.jpg`). Am I understanding right?

But maybe I am still miss something. Do you like to avoid to lose any previously saved file?

**Comment by mcicolella** [comment]
@P3trur0 I'm already capturing every image in the form camera-name_DATE_TIME.jpg.
Yes I'd like to send a notification with an attached image if required.

**Comment by P3trur0** [comment]
@mcicolella so your `ipcamera` branch does the trick very well :smile:

**Comment by mcicolella** [comment]
Fixed in https://github.com/freedomotic/freedomotic/commit/eeab11f409cc6bbb7b399a9bc7d9006cbc8a4c42
