### ISSUE TITLE
Save triggers, commands and reactions periodically

### ISSUE THREAD

**Issue by mcicolella** [freedomotic/freedomotic#230]
Now when a new trigger/command/reaction is created it's stored in memory (into a [list](https://github.com/freedomotic/freedomotic/blob/a4967cd33bb4ba967d9c7ba20304f084fc166b34/framework/freedomotic-core/src/main/java/com/freedomotic/reactions/TriggerRepositoryImpl.java#L54) and it's saved to disk only when Freedomotic stops ([onExit()](https://github.com/freedomotic/freedomotic/blob/1e26a0a4df0bef7d9e01efb3499716ed2fa7e735/framework/freedomotic-core/src/main/java/com/freedomotic/app/Freedomotic.java#L526) method). 

But if the system crashes or a blackout powers off the hardware all data in memory are lost.
Maybe we should provide a periodically saving by setting a convenient time interval to reduce the number of writing operations.
Also the folders are emptied and all data files (commands, triggers and reactions) are saved (not only new and modified ones).

**Comment by wiewioraseb** [comment]
I will be very happy to take this one.

**Comment by mcicolella** [comment]
Hi @wiewioraseb 
what's your proposal to fix it?
Thanks

**Comment by wiewioraseb** [comment]
At first I thought about creating a @Scheduled annotation that saves data, but that's Spring annotation and we don't have it here. I guess I could use Timer class  (https://docs.oracle.com/javase/8/docs/api/java/util/Timer.html)  or quartz (http://www.quartz-scheduler.org/). Any interval suggestions?

**Comment by wiewioraseb** [comment]
I will finish my PR tomorrow.

**Comment by mcicolella** [comment]
Hi @wiewioraseb 
I'd add the interval as a configuration property in config.xml (e.g. data-saving-interval).
Also I'd make this feature "optional" with a specific property in the same file, e.g. "enable-data-saving" or something similar with "on/off" values.
So users can decide if enable it or not and set its interval.

**Comment by wiewioraseb** [comment]
Thanks for the suggestions, I will count that in.

**Comment by wiewioraseb** [comment]
@mcicolella PR here #231. I will implement rest of the features tomorrow.
