### ISSUE TITLE
Add a summary to Things folder 

### ISSUE THREAD

**Issue by mcicolella** [freedomotic/freedomotic#232]
When triggers, commands and reactions are saved to disk, a summary file (index.txt) is created in the same folder (see https://github.com/freedomotic/freedomotic/blob/a4967cd33bb4ba967d9c7ba20304f084fc166b34/framework/freedomotic-core/src/main/java/com/freedomotic/reactions/CommandRepositoryImpl.java#L220)

We should create the same for things when the method `saveObjects(File folder)` is called in https://github.com/freedomotic/freedomotic/blob/c389a672f155814878586d0cd23816d2f3de36df/framework/freedomotic-core/src/main/java/com/freedomotic/things/impl/ThingRepositoryImpl.java#L98
The file index.txt should have the format
"#Filename \t #ThingName \t" where filename is its uuid.

**Comment by P3trur0** [comment]
@mcicolella I can take this :)

**Comment by mcicolella** [comment]
@P3trur0 Ok, thanks!

**Comment by dudraj** [comment]
@mcicolella Can I take this.

**Comment by mcicolella** [comment]
Hi @dudraj 
@P3trur0 is already working on this.
Thanks

**Comment by P3trur0** [comment]
HI @mcicolella, 

I've a couple of questions about this issue:

1. [Here](https://github.com/freedomotic/freedomotic/blob/c389a672f155814878586d0cd23816d2f3de36df/framework/freedomotic-core/src/main/java/com/freedomotic/things/impl/ThingRepositoryImpl.java#L126) you are already saving some XML, right? So what's the actual need to be implemented?

2. `CommandRepositoryImpl` saves the `index.xml` in `loadCommands` method, while in the issue description you ask to implement the save feature for `ThingRepositoryImpl` in the `saveObjects(File folder)`. Did I understand properly?

Thank you!

**Comment by mcicolella** [comment]
@P3trur0 
1. XML files represent the things, indext.txt is a list of them in the folder. It's a way to identify a file object quickly (more difficult from its uuid).
2. Yes we have an index.txt for commands but no one for things.

If you have a Freedomotic installation under the folder **data** you can find other subfolders as **cmd**, **trg**, **rea** and **furn**. Into the last the environments (with **obj** folder) take place. Each of them have or would have its index.txt.

Thanks

**Comment by P3trur0** [comment]
@mcicolella thank you for your reply.

I've one more doubt about question 2:

> `CommandRepositoryImpl` saves the `index.xml` in `loadCommands` method, while in the issue description you ask to implement the save feature for `ThingRepositoryImpl` in the `saveObjects(File folder)`. Did I understand properly?

The feature should be implemented in `ThingRepositoryImpl.saveObjects` or in `ThingRepositoryImpl.loadAll`?

Thank you!

**Comment by mcicolella** [comment]
@P3trur0 I got it!
You are right. I think we should implement the feature in the "save" method to consider new things created during the session and do the same also for commands, triggers and reactions.
What's your opinion?

**Comment by P3trur0** [comment]
@mcicolella yes, I do agree.

So I'd go with this implementation.

**Comment by P3trur0** [comment]
@mcicolella here you go!

I've created an utility class named `FileOperations` where, in the future, all the file utilities can be centralized.

Have a nice evening!
