### ISSUE TITLE
Upgrading Java compiler from version 7 to 8

### ISSUE THREAD

**Issue by wiewioraseb** [freedomotic/freedomotic#233]
Any particular reason freedomotic project is in Java 7 instead of Java 8? [reference](https://github.com/freedomotic/freedomotic/blob/bdc798fb59dc19d129b874baf1e1660238f66114/pom.xml#L265-L266)

Are you considering upgrading anytime soon?

**Comment by mcicolella** [comment]
@P3trur0 what about? I think there are no problems.

**Comment by P3trur0** [comment]
@mcicolella I assume it is feasible. Moreover, it'd help to clean up the source code too, since by usage of Lambdas and other tricks it can become more readable (see issue #270).
