### ISSUE TITLE
Workflow for doc contribution

### ISSUE THREAD

**Issue by mcicolella** [freedomotic/freedomotic#235]
We need help to write and update our documentation.
In particular we should define a good workflow for that.
Technical doc is based on Github wiki. Opening it to external contributes requires to create a specific repo (cloning the official one) and then syncronize the two.
This should be done by CI system.
This is an example http://www.growingwiththeweb.com/2016/07/enabling-pull-requests-on-github-wikis.html
Also we'd like to create a good downloadable doc (PDF) from the wiki pages.
Any idea? We could use ReadTheDocs but this requires some scripts to
1. read the wiki pages
2. format (convert if required) them in a nice way
3. update ReadTheDocs 

Other solutions?

**Comment by mcicolella** [comment]
For now we could mantain the wiki for tech documentation using a specific repo to manage PRs and start with ReadTheDocs for the user manual (actually we have only a few pages on the site http://freedomotic.com/content/users-tutorial). 

@P3trur0 Your opinion?

**Comment by P3trur0** [comment]
@mcicolella I agree to go with ReadTheDocs. It is a really good tool.
Personally I have no direct experience in setting up a repository using it, but browsing documentation built by ReadTheDocs is awesome.

I'd go with a separate repository for documentation and a CI environment to run some script performing the actual documentation generation (e.g.: [Sphinx](http://www.sphinx-doc.org/en/1.4.8/))

**Comment by mcicolella** [comment]
I'm starting with a repository for users' documentation (e.g. fd-user-guide) to manage with ReadTheDocs.
The first step is to prepare a **topics index**.
Any idea?

**Comment by amenak77** [comment]
Hi,
As user's documentation the critical problems, in my opinion are all related to jfrontend, which is the main interface with Freedomotic. In particular I'd be rich in details about:
- Environment creation
- Environment personalization
- Multi floor management
- Plugins management and how to deal with marketplace
Plugins aren't usually very critical except some plugins which are quite specific and have its own gui (such as OpenWebNet plugin), but plugin GUI's functions are usually redundant
- Freedomotic headless and management in command line window
Point two is quite useful because contains the chapter related to object management:
- create object (with details about join device function)
- delete object
- edit object (every single tag explained)
Missing something?

**Comment by amenak77** [comment]
Hi again,
Missed a lot of things ;) As a manual for users we should begin with a
- General part and a subtitle "What is Freedomotic?" speaking also about open source, GPL2 licence and contribution. Moreover all references to Freedomotic group and website
- Fredomotic GUI Jfrontend with all points already described; in particular point three (plugins) needs a description of manifest.xml file (What is, Where is, and How to modify it) 
- Use cases, university's projects, who is using Fredomotic around the world (strange surprises sometimes)
- Bibliography and iconography
Again, missing something? Have a nice evening, Alberto

**Comment by mcicolella** [comment]
@amenak77 Thanks! Good points!

**Comment by mcicolella** [comment]
Hi all
I'm setting the skeleton of the manual before moving it on the official repository. In this phase I'm defining a TOC as a working guide so please comment if you have any suggestions: titles, chapters and how to order them.
The demo is available at https://freedomotic-test-mcicolella.c9users.io/docs/build/html/index.html (work in progress)

**Comment by mcicolella** [comment]
I like much the Jupyter doc (http://jupyter.readthedocs.io/en/latest/)

**Comment by amenak77** [comment]
Hi @mcicolella good work! The only thing I'd change is putting in main menu the point "freedomotic headless" and "freedomotic running in command line window"; just to give them the right kind of visibilitiy. I presume you thought about a sub chapter inside "basic configuration" or "jfrontend plugin". Not a so great problem however. Well done, thank you

**Comment by amenak77** [comment]
I like the jupiter doc too!  +1

**Comment by P3trur0** [comment]
@mcicolella [this](https://github.com/freedomotic/freedomotic/issues/235#issuecomment-258100588) rocks!

**Comment by amenak77** [comment]
@P3trur0 Thank you very much for your great contribution to freedomotic project

**Comment by mcicolella** [comment]
Updated to the Jupyter theme but I must review the layout and change the colours.

**Comment by amenak77** [comment]
It looks great! There was also a big logo in the upper left side ;)

**Comment by mcicolella** [comment]
The structure is ready! Many contents must be updated. Take a look at https://freedomotic-test-mcicolella.c9users.io/docs/build/html/index.html

**Comment by mcicolella** [comment]
The first demo is available on RTD http://fd-user-manual.readthedocs.io/en/latest/ - http://readthedocs.org/projects/fd-user-manual/downloads/pdf/latest/
A lot of work to do!

**Comment by amenak77** [comment]
Hi,
@mcicolella GREAT WORK!!!

**Comment by mcicolella** [comment]
I'm closing this issue because now we have a specific repository for user manual https://github.com/freedomotic/fd-user-manual
All related issues can be opened there.
Thanks
