### ISSUE TITLE
freedomotic-model pom.xml should contain a <pluginManagement> tag

### ISSUE THREAD

**Issue by P3trur0** [freedomotic/freedomotic#238]
The **freedomotic-model** Maven project does not build if opened with Eclipse IDE, due to [this error](https://www.eclipse.org/m2e/documentation/m2e-execution-not-covered.html) in the M2E plugin.

Then, in order to allow a proper compilation of **freedomotic-model** Maven project with Eclipse IDE the **<plugins>** section of the pom.xml should be wrapped in the **<pluginManagement>** tag. Like this:

```xml
...
  <build>
<pluginManagement>
<plugins>
...
</plugins> 
 </pluginManagement>
  </build>
```

**Comment by mcicolella** [comment]
Can you submit a PR for this? 
Thanks

**Comment by P3trur0** [comment]
@mcicolella here you go,
