### ISSUE TITLE
Problem install reactions from plugin

### ISSUE THREAD

**Issue by rtrive** [freedomotic/freedomotic#241]
Hi, i've noticed some problem with reactions when i coding my plugins.
I create a folder data/rea to insert the .xrea file but when the the core try to load all reactions it comes out with an error: "comand xxx not found".
Here's the problema, the command exists. I try to load manually the file .xrea on framework-core/data/rea instead of folder rea on my plugin and with this method there's no problem. 

![log_error](https://cloud.githubusercontent.com/assets/6997999/20936410/ce4dc100-bbe2-11e6-8495-d597c617e600.png)

My opinion about this is that the core load reactions before loading objects so it doesn't found any commands.

**Comment by mcicolella** [comment]
@futurama92 do you have this problem only with commands related to objects (e.g. Turn on/off object-name) ? In other words is the exception raised only with commands created dinamically?

**Comment by futurama92** [comment]
the answers are yes for both questions
