### ISSUE TITLE
Add a generic property to identify events or command payloads 

### ISSUE THREAD

**Issue by P3trur0** [freedomotic/freedomotic#247]
Currently, there is no easy way to detect if a set of payload properties contained in objects belong to Command or Events.
It could be useful to add a generic property, while building the instance, to flag if the payload is either of an Event or of a Command.

For example, in the case of Events `EventTemplate` class, it could be added (e.g.: [here](https://github.com/freedomotic/freedomotic/blob/master/framework/freedomotic-core/src/main/java/com/freedomotic/api/EventTemplate.java#L164)) something like  

`payload.setProperty("type","event")`

**Comment by mcicolella** [comment]
@enriconicoletti what about?
