### ISSUE TITLE
Building of armhf (32 bit) Docker image failed

### ISSUE THREAD

**Issue by mcicolella** [freedomotic/freedomotic#252]
[This ](https://hub.docker.com/r/freedomotic/freedomotic/builds/bqmegxi3tets7rschie72fe/ )is the log.

In particular the reported error is `Build failed: The command '/bin/sh -c apt-get update && apt-get upgrade -y' returned a non-zero code: 2` .

The other images (for amd64) are OK. Any idea?

**Comment by P3trur0** [comment]
I am not expert about Docker, but maybe the problem could be the same described [here](https://github.com/docker-library/mysql/issues/228)

**Comment by mcicolella** [comment]
@P3trur0 
Infact by default Docker Hub manages only amd64 images. 
But I found a solution based on qemu and powered by resin.io. The building is OK but I have to test it on a Raspberry or another arm 32 bit platform
[Here](https://github.com/mcicolella/docker-examples/blob/master/Dockerfile) the dockerfile.
Now I need an image for arm64.

**Comment by mcicolella** [comment]
Also it installs the[ Zulu Embedded JDK](https://www.azul.com/downloads/zulu/zdk-8-ga-linux_aarch32hf.tar.gz) that is considered one of the best implementation for these boards.

**Comment by paridhika** [comment]
@P3trur0
Hi,
I cannot see your file. can you please share it

**Comment by paridhika** [comment]
@mcicolella 
Hi, I cannot see your file can you please share it.
