### ISSUE TITLE
Each freedomotic instance should have a final identifier

### ISSUE THREAD

**Issue by P3trur0** [freedomotic/freedomotic#256]
Currently, when a freedomotic instance starts, it checks if a UUID for the current instance has been provided at startup, otherwise it creates a new random identifier.

However, this random identifier, is not persisted, so at each freedomotic restart the identifier changes again.

It could be useful to persist this generated id somewhere, for example in the `config.xml`.

**Comment by P3trur0** [comment]
Solved by #257.

**Comment by mcicolella** [comment]
Fixed by #257
