### ISSUE TITLE
jfrontend "freeze" bug

### ISSUE THREAD

**Issue by amenak77** [freedomotic/freedomotic#259]
When Freedomotic runs as an icon in OS traybar, Freedomotic's GUI, the jfrontend doesn't update Freedomotic objects status, so there is an "out of synchro" between objects status and their representation in the GUI when the framework pops up from the traybar. We called this bug "freeze"

**Comment by P3trur0** [comment]
I'll give it a try!

**Comment by mcicolella** [comment]
Fixed in #261
