### ISSUE TITLE
Plugin.java throws NPE when not file path is provided for configuration

### ISSUE THREAD

**Issue by P3trur0** [freedomotic/freedomotic#275]
[This constructor](https://github.com/freedomotic/freedomotic/blob/97ad4ddff46d8f0f6cf9ac525b9b95e7a85a40d5/framework/freedomotic-core/src/main/java/com/freedomotic/api/Plugin.java#L107) method in `Plugin` class is NPE prone since it throws NPE when no `path` variable is provided.

Indeed, when it enters the `if` branch [here](https://github.com/freedomotic/freedomotic/blob/97ad4ddff46d8f0f6cf9ac525b9b95e7a85a40d5/framework/freedomotic-core/src/main/java/com/freedomotic/api/Plugin.java#L465), the following method call:

```java
    private void deserializeManifest(File manifest)
```
throws a NullPointerException.

**Comment by mcicolella** [comment]
#270

**Comment by mcicolella** [comment]
Fixed in #278
