### ISSUE TITLE
Adopt a minimal image for Docker

### ISSUE THREAD

**Issue by mcicolella** [freedomotic/freedomotic#283]
Currently we are using java:8-jre in our [Dockerfile](https://github.com/freedomotic/freedomotic/tree/master/scripts/docker/amd64) but it is a large image and there could be licensing problems with redistribution.
For example we could adopt https://hub.docker.com/r/anapsix/alpine-java/ or another one.

**Comment by GaruGaru** [comment]
I'd like to work at this issue,  i'll make some tests to find out which image between the one that you suggested and open-jdk:8u131-jre-alpine is the best fit

**Comment by mcicolella** [comment]
Hi @GaruGaru 
thanks for your support. Sure you can work on this issue. Also, if you want, you can take a look at the other Docker images (for ARM) and suggest any improvement based on your experience.

**Comment by GaruGaru** [comment]
I'll surely give the dockerfile for arm a look, and what about adding a docker-compose in order to ease the container setup ?

**Comment by haroon-sheikh** [comment]
@GaruGaru docker-compose is very helpful for local development, but I would personally advise you not to use that when integrating within CI configuration.

**Comment by mcicolella** [comment]
@GaruGaru can you explain your idea about docker-compose?

**Comment by angelbarrera92** [comment]
Take a look to the PR9 #318 
:)

**Comment by mcicolella** [comment]
@angelbarrera92 thanks. @GaruGaru proposed an alternative image. Also have you tried it?

**Comment by angelbarrera92** [comment]
Ive tried the proposed PR and it works. It is the same image but with different tags. Whith my base image you can fetch all new jre8 revisions instead of stay fixed in version.

**Comment by angelbarrera92** [comment]
Is there any problem? Do you need anithing else?

**Comment by mcicolella** [comment]
Thanks to @angelbarrera92 we have a new image of 213 MB. This could be the official one.
https://hub.docker.com/r/freedomotic/freedomotic/tags/

**Comment by mcicolella** [comment]
This #356 PR further reduce the image size. Now it is 99MB.

**Comment by mcicolella** [comment]
@thobalose  what about adding a HEALTHCHECK?

**Comment by thobalose** [comment]
Hi @mcicolella ,

You mean having something like:

 ```sh 
HEALTHCHECK --interval=5s --timeout=3s CMD curl -f --user admin:admin http://0.0.0.0:9111/v3/system/info/messaging || exit 1
```

```sh
HEALTHCHECK --interval=5s --timeout=3s CMD curl -fI http://0.0.0.0:8090 || exit 1
```
in the `Dockerfile`.

**Comment by mcicolella** [comment]
I'm closing this issue. Thanks to all for your support.
