### ISSUE TITLE
Add/update a translation for your language

### ISSUE THREAD

**Issue by mcicolella** [freedomotic/freedomotic#284]
Freedomotic supports more than 20 languages using Transifex.
We are searching contributors for new languages or existing translations.

Solution 1 (recommanded in particular for a new language)
1. Join our team on Transifex (https://www.transifex.com/freedomotic/freedomotic-open-source-buildi/)
2. Complete the translation
3. Download the file .properties and submit a PR

Solution 2
1. Work directly on the files in https://github.com/freedomotic/freedomotic/tree/master/framework/freedomotic-core/i18n and https://github.com/freedomotic/freedomotic/tree/master/plugins/devices/frontend-java/src/main/resources/data/i18n 
2. Submit a PR

If you want to apply please add a comment here so we can open a specific issue and track
the tasks.

**Comment by AbhilashG97** [comment]
Hello @mcicolella ,
I would love to help you with translations in Hindi (hi). May I proceed ?

**Comment by mcicolella** [comment]
Hi @AbhilashG97 ,
ok for Hindi. Thanks

**Comment by Haxk20** [comment]
Hello @mcicolella ,
I would love to help you transtate it to Slovak (sk).
If you agree i will send my PR at 1st October.

**Comment by mavega998** [comment]
I will like translate to spanish

**Comment by mcicolella** [comment]
@Haxk20 Ok, thanks.

**Comment by mcicolella** [comment]
@mavega998 Ok, thanks.

**Comment by hi-hi-ray** [comment]
Hi, i'm finishing translate Pt-Br and i'll review the things that needed to be reviewed . =]

**Comment by mohamed-habib** [comment]
Hi, I will work on Arabic.

**Comment by lex111** [comment]
@mcicolella Hello! I am ready to complete the translation for the Russian.

**Comment by mcicolella** [comment]
@hi-hi-ray Ok, thanks

**Comment by mcicolella** [comment]
@mohamed-habib do you want to use Transifex?

**Comment by mcicolella** [comment]
@lex111 Ok, thanks.

**Comment by mohamed-habib** [comment]
No, I will just create the .properties files and translate.

**Comment by the7th** [comment]
Hi, I can help with Malaysian Malay language :)

**Comment by mcicolella** [comment]
@the7th do you want to use Transifex?

**Comment by the7th** [comment]
@mcicolella nah, I'll submit a PR :)

**Comment by LeonoraG** [comment]
Hi, @mcicolella  I'd like to help with missing Croatian translations for telegram-bot and fd-polymer-i18next-translate.

**Comment by mcicolella** [comment]
@LeonoraG Ok, thanks.

**Comment by lex111** [comment]
@mcicolella Can you give me access to transifex? The fact is that it shows 20 lines for translation, and I see much less than in the files in which I need to make a translation.

**Comment by mcicolella** [comment]
@lex111 done

**Comment by lex111** [comment]
@mcicolella It is unclear whether to translate `telegram-bot-plugin`?

**Comment by bkruczyk** [comment]
@mcicolella I can help with filling in polish translation

**Comment by Nina029** [comment]
I would like to add german

**Comment by mcicolella** [comment]
@bkruczyk Ok.

**Comment by mcicolella** [comment]
@Nina029 Ok.

**Comment by mavega998** [comment]
Hi, the Spanish translation is complete. If I can help, you don't dudes in tell me.

**Comment by krns** [comment]
German translations in the making or should I do it this weekend?

**Comment by balachandarsv** [comment]
Shall i take it up for tamil?

**Comment by mcicolella** [comment]
@krns you can work on German translations if you want.

**Comment by mcicolella** [comment]
@balachandarsv ok

**Comment by sixdouglas** [comment]
Hi there was some missing translation for a keys in French. I've created a PR for them:
https://github.com/freedomotic/freedomotic/pull/389
Hope it helps

**Comment by Philip-Nicolas** [comment]
I can work on French translation.

**Comment by nmenego** [comment]
Hi will work on the Philippine and Japanese translations.

**Comment by samcarecho** [comment]
Is someone translating to Portuguese?
