### ISSUE TITLE
Code gardening of Renderer class

### ISSUE THREAD

**Issue by mcicolella** [freedomotic/freedomotic#287]
Remove all issues reported by [Sonarcloud](https://sonarcloud.io/dashboard?id=com.freedomotic%3Afrontend-java%3Asrc%2Fmain%2Fjava%2Fcom%2Ffreedomotic%2Fjfrontend%2FRenderer.java). 

PLEASE BE CAREFUL BEFORE SENDING A PR
- Double check every issue with great attention. Sonarcloud sometimes reports 'false' issues (e.g. unused variables but they are really used). In case of doubt ask our team
- Compile the code
- Run the code to be sure there aren't runtime exceptions
- If you want to propose a better implementation please add a comment describing your proposal of refactoring
- Submit a PR with a single commit

**Comment by P3trur0** [comment]
@mcicolella I can take this too.

**Comment by mcicolella** [comment]
Fixed in 0c93fd6f496813a45f43d82025a912a6c7f2b046
