### ISSUE TITLE
Code gardening of MessageEvent class and add unit tests

### ISSUE THREAD

**Issue by mcicolella** [freedomotic/freedomotic#302]
Remove all issues reported by [Sonarcloud](https://sonarcloud.io/dashboard?id=com.freedomotic%3Afreedomotic-core%3Asrc%2Fmain%2Fjava%2Fcom%2Ffreedomotic%2Fevents%2FMessageEvent.java) and add unit tests.

PLEASE BE CAREFUL BEFORE SENDING A PR

1.Double check every issue with great attention. Sonarcloud sometimes reports 'false' issues (e.g. unused variables but they are really used). In case of doubt ask our team
2.Compile the code
3.Run the code to be sure there aren't runtime exceptions
4.If you want to propose a better implementation please add a comment describing your proposal of refactoring
5.Submit a PR with a single commit

**Comment by P3trur0** [comment]
@mcicolella may I take this, please?

**Comment by mcicolella** [comment]
@P3trur0 Yes!

**Comment by mcicolella** [comment]
Fixed in aeef1b2a4294fc0be62d83c4aeac0ad3845ab88f and 66c6d7e9484ccb77b9b948f31e466906e2680cef
