### ISSUE TITLE
Code gardening of TcpHelper class

### ISSUE THREAD

**Issue by mcicolella** [freedomotic/freedomotic#306]
Remove all issues reported by [Sonarcloud](https://sonarcloud.io/dashboard?id=com.freedomotic%3Afreedomotic-core%3Asrc%2Fmain%2Fjava%2Fcom%2Ffreedomotic%2Fhelpers%2FTcpHelper.java).

PLEASE BE CAREFUL BEFORE SENDING A PR

1.Double check every issue with great attention. Sonarcloud sometimes reports 'false' issues (e.g. unused variables but they are really used). In case of doubt ask our team
2.Compile the code
3.Run the code to be sure there aren't runtime exceptions
4.If you want to propose a better implementation please add a comment describing your proposal of refactoring
5.Submit a PR with a single commit

**Comment by P3trur0** [comment]
Since it is an acronym is it worth to rename the class also to `TCPHelper`?

**Comment by mcicolella** [comment]
I think so.

**Comment by delbertlegg** [comment]
@mcicolella @P3trur0 I can take this on

**Comment by P3trur0** [comment]
:+1:

**Comment by mcicolella** [comment]
Fixed in fea39b3f9c2c9b8143812ab65580c33abe356997
