### ISSUE TITLE
Code gardening of User class and add unit tests

### ISSUE THREAD

**Issue by mcicolella** [freedomotic/freedomotic#308]
Remove all issues reported by [Sonarcloud]([url](https://sonarcloud.io/dashboard?id=com.freedomotic%3Afreedomotic-core%3Asrc%2Fmain%2Fjava%2Fcom%2Ffreedomotic%2Fsecurity%2FUser.java)) and add unit tests.

PLEASE BE CAREFUL BEFORE SENDING A PR

1.Double check every issue with great attention. Sonarcloud sometimes reports 'false' issues (e.g. unused variables but they are really used). In case of doubt ask our team
2.Compile the code
3.Run the code to be sure there aren't runtime exceptions
4.If you want to propose a better implementation please add a comment describing your proposal of refactoring
5.Submit a PR with a single commit

**Comment by P3trur0** [comment]
I take this too, if you please.

**Comment by mcicolella** [comment]
Ok.

**Comment by mcicolella** [comment]
Fixed in 2b2239cf586bf8e1a02be8563db7cc450efd8dc5 and d86c3a10838221b087f8847dcf7d5bef11000875
