### ISSUE TITLE
Update javadoc of Autodiscovery class

### ISSUE THREAD

**Issue by mcicolella** [freedomotic/freedomotic#314]
Javadoc of [Autodiscovery ](https://github.com/freedomotic/freedomotic/blob/9a01f1442828b0f9cfb06ab3a0baf37e7a45e8b1/framework/freedomotic-core/src/main/java/com/freedomotic/core/Autodiscovery.java)class.

1. Please follow the official style guide conventions http://www.oracle.com/technetwork/java/javase/documentation/index-137868.html
2. Review texts and fix typos and/or grammatical errors
3. If something is not clear please ask our team

**Comment by delbertlegg** [comment]
@mcicolella I can take this on

**Comment by mcicolella** [comment]
Fixed in 051611f2a233e7aebd681bd49842da2d65f44b14
