### ISSUE TITLE
Code gardening and Javadoc update of PeriodicSave class

### ISSUE THREAD

**Issue by mcicolella** [freedomotic/freedomotic#319]
Remove all issues reported by [Sonarcloud ](https://sonarcloud.io/code?id=com.freedomotic%3Afreedomotic&selected=com.freedomotic%3Afreedomotic-core%3Asrc%2Fmain%2Fjava%2Fcom%2Ffreedomotic%2Futil%2FPeriodicSave.java) and update/complete Javadoc.

PLEASE BE CAREFUL BEFORE SENDING A PR

1. Double check every issue with great attention. Sonarcloud sometimes reports 'false' issues (e.g. unused variables but they are really used). In case of doubt ask our team
2. For Javadoc please follow the official style guide conventions http://www.oracle.com/technetwork/java/javase/documentation/index-137868.html
3. Review texts and fix typos and/or grammatical errors
4. Compile the code
5. Run the code to be sure there aren't runtime exceptions
6. If you want to propose a better implementation please add a comment describing your proposal of refactoring
7. Submit a PR with a single commit

**Comment by srikanthnakka** [comment]
I would like to work on this issue.

**Comment by mcicolella** [comment]
Ok.

**Comment by srikanthnakka** [comment]
PR is completed 
https://github.com/freedomotic/freedomotic/pull/320
