### ISSUE TITLE
Code gardening and Javadoc update of MarketPlacePlugin2 class

### ISSUE THREAD

**Issue by mcicolella** [freedomotic/freedomotic#323]
Remove all issues reported by [Sonarcloud](https://sonarcloud.io/dashboard?id=com.freedomotic%3Afreedomotic-drupal-marketplace%3Asrc%2Fmain%2Fjava%2Fcom%2Ffreedomotic%2Fmarketplace%2Futil%2FMarketPlacePlugin2.java) and update/complete Javadoc.

PLEASE BE CAREFUL BEFORE SENDING A PR

1.Double check every issue with great attention. Sonarcloud sometimes reports 'false' issues (e.g. unused variables but they are really used). In case of doubt ask our team
2.For Javadoc please follow the official style guide conventions http://www.oracle.com/technetwork/java/javase/documentation/index-137868.html
3.Review texts and fix typos and/or grammatical errors
4.Compile the code
5.Run the code to be sure there aren't runtime exceptions
6.If you want to propose a better implementation please add a comment describing your proposal of refactoring
7.Please REBASE your working branch and SUBMIT a single commit PR

**Comment by allienna** [comment]
I take it

**Comment by mcicolella** [comment]
@allienna Ok.

**Comment by allienna** [comment]
Can you assign it to me

**Comment by allienna** [comment]
In fact, I don't know what's this file do. So, I let it for any other developer.
