### ISSUE TITLE
Code gardening and Javadoc update of AbstractConsumer class 

### ISSUE THREAD

**Issue by mcicolella** [freedomotic/freedomotic#324]
Remove all issues reported by [Sonarcloud](https://sonarcloud.io/dashboard?id=com.freedomotic%3Afreedomotic-core%3Asrc%2Fmain%2Fjava%2Fcom%2Ffreedomotic%2Fapi%2FAbstractConsumer.java) and update/complete Javadoc.

PLEASE BE CAREFUL BEFORE SENDING A PR

1.Double check every issue with great attention. Sonarcloud sometimes reports 'false' issues (e.g. unused variables but they are really used). In case of doubt ask our team
2.For Javadoc please follow the official style guide conventions http://www.oracle.com/technetwork/java/javase/documentation/index-137868.html
3.Review texts and fix typos and/or grammatical errors
4.Compile the code
5.Run the code to be sure there aren't runtime exceptions
6.If you want to propose a better implementation please add a comment describing your proposal of refactoring
7.Please REBASE your working branch and SUBMIT a single commit PR

Notes:
1. Don't remove TODO lines
2. Substitute RuntimeException with FreedomoticRuntimeException

**Comment by yirrilo** [comment]
Hello,

I'll do it if you're OK

Yann

**Comment by mcicolella** [comment]
@yirrilo ok
