### ISSUE TITLE
Code formatter

### ISSUE THREAD

**Issue by allienna** [freedomotic/freedomotic#326]
I think that's a good idea to use Google style as formatter for java code 

https://github.com/google/styleguide/blob/gh-pages/intellij-java-google-style.xml

**Comment by P3trur0** [comment]
@allienna thank you for the proposal! Let's consider that. Moreover it could be useful to introduce directly in the CI also a static analysis tool (via Maven plugin, for example) to assess the proper code formatting during the build itself.

For example [Qulice](http://www.qulice.com/) does a great job in this field.

**Comment by mcicolella** [comment]
What about opening a dedicated issue for Qulice?

**Comment by P3trur0** [comment]
@mcicolella why not! Maybe it is good to define a good configuration for it since it is quite _aggressive_ by default :)

**Comment by mcicolella** [comment]
@P3trur0 can you open it?

**Comment by P3trur0** [comment]
@mcicolella #359

**Comment by mcicolella** [comment]
@P3trur0 can we close this?

**Comment by P3trur0** [comment]
@mcicolella according to me it is useful to have a reminder about code style/formatting. However we already have #270 for this.
