### ISSUE TITLE
Code gardening and Javadoc update of HttpHelper class

### ISSUE THREAD

**Issue by mcicolella** [freedomotic/freedomotic#342]
Remove all issues reported by [Sonarcloud ](https://sonarcloud.io/dashboard?id=com.freedomotic%3Afreedomotic-core%3Asrc%2Fmain%2Fjava%2Fcom%2Ffreedomotic%2Fhelpers%2FHttpHelper.java)and update Javadoc.

PLEASE BE CAREFUL BEFORE SENDING A PR

1. Double check every issue with great attention. Sonarcloud sometimes reports 'false' issues (e.g. unused variables but they are really used). In case of doubt ask our team
2. For Javadoc please follow the official style guide conventions http://www.oracle.com/technetwork/java/javase/documentation/index-137868.html
3. Review texts and fix typos and/or grammatical errors
4. Compile the code
5. Run the code to be sure there aren't runtime exceptions
6. If you want to propose a better implementation please add a comment describing your proposal of refactoring
7. Submit a PR with a single commit

**Comment by mardibiase** [comment]
Hi @mcicolella, I am working a bit on this issue. 
What would you like to improve in HttpHelper? 
I am just fixing some javadoc and addressing the warning at [line 164](https://github.com/freedomotic/freedomotic/blob/master/framework/freedomotic-core/src/main/java/com/freedomotic/helpers/HttpHelper.java#L164).

**Comment by mcicolella** [comment]
hi @mardibiase for now only fixing warnings/issues and javadoc. Thanks
