### ISSUE TITLE
Introduce a Static Analysis tool

### ISSUE THREAD

**Issue by P3trur0** [freedomotic/freedomotic#359]
In order to make the code cleaner and compliant with a specific code style it could be useful to introduce a tool performing static analysis.

So far, we're considering to introduce [Qulice](http://www.qulice.com/) that is a Maven Plugin integrating a series of third party tool doing the job.

However, since its own behavior is quite restrictive on the source code compliance it is adviced to try it for a while to see if it suits our actual needs.

See #326 for further info.

**[Here](http://www.yegor256.com/2014/08/13/strict-code-quality-control.html) it is a blog post explaining the value of using Qulice**

**Comment by mcicolella** [comment]
@abollaert what do you think?

**Comment by joergsesterhenn** [comment]
I'd like to have a go at this one. I would do this if thats alright with you:
* Introduce Qulice in the build, triggered by a profile "qulice" that needs to be actively called like 'mvn clean install -Pqulice 
Once you decide you are happy with the results you can turn on the profile by default.

Would that do @P3trur0 , @mcicolella ?

**Comment by joergsesterhenn** [comment]
Qulice stops the build after the first module:
`Failed to execute goal com.qulice:qulice-maven-plugin:0.17:check (default) on project freedomotic-model: Failure: There are 2352 violations`

Since the premise of qulice seems to be "take our policy and stick to it" I don't think it makes sense to use this unless you really want to stick to the defaults of qulice.

I'd suggest to just rely on sonarcloud and integrate that into your ci pipeline in teamcity...

**Comment by P3trur0** [comment]
@joergsesterhenn thank you for your effort in evaluating Qulice. As I said it is quite restrictive in its usage.

@mcicolella what do you think? By adding Qulice it means to rewrite a lot of source code to make it working properly (for example by renaming either method or variable names). Alternatively we could consider any of the tools wrapped in qulice, for example PMD or FindBugs and see if a specific configuration of one of those could fit our needs.

Opinions anyone?

**Comment by abollaert** [comment]
Can't it be configured with excludes/includes to implement this piecemeal?

Op 16 okt. 2017 11:50 a.m. schreef "Peter Pan" <notifications@github.com>:

**Comment by P3trur0** [comment]
@abollaert AFAIK, qulice does not offer too much configuration. The only way to disable checks is to define Java annotations (one for each type of static check) on each part of the source code you'd like to avoid to check.

**Comment by abollaert** [comment]
According to http://www.qulice.com/qulice-maven-plugin/check-mojo.html you
have some leeway but it's indeed pretty limited.

Op 16 okt. 2017 12:57 p.m. schreef "Peter Pan" <notifications@github.com>:

**Comment by abollaert** [comment]
Also http://www.qulice.com/qulice-maven-plugin/example-exclude.html

Op 16 okt. 2017 1:04 p.m. schreef "Alexander Bollaert" <
alexander.bollaert@gmail.com>:

**Comment by abollaert** [comment]
I suppose you could start by trying to exclude *everything*, enable a particular check on some select part of the code, get it fixed, and iterate on that. That said, even if that works, it'll be a bit of an ugly process until all issues are fixed. But I guess that would be better than nothing?

**Comment by abollaert** [comment]
Refer to PR #381, disabled all checks using excludes. I also had to skip the plugin entirely in the device archetype, because of the "#set" stuff in HelloWorld.java

**Comment by abollaert** [comment]
Also note: this PR configures the excludes globally, but you can override this in submodules (like the archetype for example). So if you would want to go start fixing the issues reported, it would probably be easiest just to pick a module, override the parent configuration there, and start hacking on it.

**Comment by joergsesterhenn** [comment]
Why would you bother with this? you can use sonarcloud + sonarlint in eclipse and just be done with static analysis. It is so much better to manage than any maven plugin could ever be and integrates well in the delivery pipeline.

**Comment by abollaert** [comment]
The upside of this is that it enforces a particular set of practices. That
and that it does not rely on an external service. That said, I think you're
right in that it's probably not worry the hassle as SonarCloud is a really
good alternative, and that should be more than sufficient for most projects.

Op 16 okt. 2017 8:54 p.m. schreef "joergsesterhenn" <
notifications@github.com>:

**Comment by joergsesterhenn** [comment]
With sonarlint you have faster feedback than any maven plugin can offer and more help in fixing issues. Have you tried it? http://www.sonarlint.org/ It is freely available for Eclipse, IntelliJ and VisualStudio (Code). And you can use it connected or offline.
I'd also recommend to implement a deployment pipeline in Teamcity that triggers sonarcloud scans after successful builds.

**Comment by mcicolella** [comment]
No, I haven't tried it. No available for NetBeans.

**Comment by abollaert** [comment]
You don't need a pipeline for that? You could just add the
maven-sonar-plugin in an integration build profile, this will keep it
independent from TeamCity (you could for example also use Travis instead).
I second SonarLint btw, works pretty well in Eclipse (some of my colleagues
use it in IntelliJ too, no complaints).

**Comment by joergsesterhenn** [comment]
@mcicolella,  netbeans? maybe you should introduce a new tool right there 🤓. Just kidding, to each his own demise 😉
The maven-sonar-plugin does not give you detailed feedback in the IDE like sonarlint. 
There is however a netbeans plugin for sonarqube ( http://plugins.netbeans.org/plugin/51532/radar-netbeans ). Maybe give that a try. Sonarqube in my opinion is way better in helping you to improve your coding than all of the pmd, checkstyle, findbugs/spotbugs, ... (you name it) out there.
By pipeline I meant that you setup an integration build that runs **after** every successful build and informs you if you reached your defined quality gate. This is not specific to teamcity - just saw that you are using teamcity.

**Comment by mcicolella** [comment]
We decided to continue with Sonarqube. 
Thanks to all.
