### ISSUE TITLE
Code gardening and Javadoc update of PluginConfigure class

### ISSUE THREAD

**Issue by mcicolella** [freedomotic/freedomotic#367]
Remove all issues reported by [Sonarcloud](https://sonarcloud.io/dashboard?id=com.freedomotic%3Afrontend-java%3Asrc%2Fmain%2Fjava%2Fcom%2Ffreedomotic%2Fjfrontend%2FPluginConfigure.java) and update/complete Javadoc.

PLEASE BE CAREFUL BEFORE SENDING A PR

1.Double check every issue with great attention. Sonarcloud sometimes reports 'false' issues (e.g. unused variables but they are really used). In case of doubt ask our team
2.For Javadoc please follow the official style guide conventions http://www.oracle.com/technetwork/java/javase/documentation/index-137868.html
3.Review texts and fix typos and/or grammatical errors
4.Compile the code
5.Run the code to be sure there aren't runtime exceptions
6.If you want to propose a better implementation please add a comment describing your proposal of refactoring
7.Please REBASE your working branch and SUBMIT a single commit PR

**Comment by bezmax** [comment]
Hello @mcicolella . I'd like to work on this issue and also have a question.

There seem to be a lot of problems in Sonar related to Swing components being serializable. AFAIK this can be used for thin clients or for restoring UI from persisted states. I do not think that anything like that will ever be needed by the project or is planned currently, that is - swing components will never be serialized.

I can also see that some of the other commits (like ecf1c1a0a4d42a59080ab2df945690202bcd65a5) have tried to address the issue by just slapping `transient` all around those UI components. I do not think this is a correct approach, given my previous arguments.

My proposal would be to just disable the check for all UI components with `@SuppressWarnings("squid:S1948")` and a comment explaining the reason. What do you think, should I add @SuppressWarnings, or just go with `transient` everywhere?

**Comment by mcicolella** [comment]
@bezmax thanks for your remarks.
Maybe it'd better to discuss about the serialization of Swing components (using "transient" keyword or "@SuppressWarnings") in a specific issue. So we can adopt the same approach in every file.
For now I'm integrating this PR. Thanks
