### ISSUE TITLE
Code gardening and Javadoc update of PluginJList class 

### ISSUE THREAD

**Issue by mcicolella** [freedomotic/freedomotic#371]
Remove all issues reported by [Sonarcloud](https://sonarcloud.io/code?id=com.freedomotic%3Afreedomotic&selected=com.freedomotic%3Afrontend-java%3Asrc%2Fmain%2Fjava%2Fcom%2Ffreedomotic%2Fjfrontend%2FPluginJList.java) and update/complete Javadoc.

PLEASE BE CAREFUL BEFORE SENDING A PR

1.Double check every issue with great attention. Sonarcloud sometimes reports 'false' issues (e.g. unused variables but they are really used). In case of doubt ask our team
2.For Javadoc please follow the official style guide conventions http://www.oracle.com/technetwork/java/javase/documentation/index-137868.html
3.Review texts and fix typos and/or grammatical errors
4.Compile the code
5.Run the code to be sure there aren't runtime exceptions
6.If you want to propose a better implementation please add a comment describing your proposal of refactoring
7.Please REBASE your working branch and SUBMIT a single commit PR

**Comment by gubbaraviteja** [comment]
@mcicolella I would like to work on this. I will ask here if I've any questions.

**Comment by gubbaraviteja** [comment]
@mcicolella 
I've followed the steps in README file and encountered an error while compiling the code. 
From googling, I came to know that we need to generate certificate and add it to JVM. But the question is, if everyone need to do this step, shouldn't we add this in README file?
Below is the snapshot of error log.
![image](https://user-images.githubusercontent.com/9277498/31580372-f829cac6-b14d-11e7-9206-2ad313986157.png)

**Comment by gubbaraviteja** [comment]
For now, I've solved it by replacing the outputTemplate value to take the template from src/main/resources instead of https://raw.github.com.

![image](https://user-images.githubusercontent.com/9277498/31582843-c9476f60-b18e-11e7-8b17-d2ad224bbcb7.png)

But please let me know how to get rid of this issue in correct approach.

**Comment by mcicolella** [comment]
@gubbaraviteja it's the first time I see this issue. Never required a certificate. On NetBeans and Eclipse is all ok and the same for our CI Teamcity and Codeship.

**Comment by gubbaraviteja** [comment]
@mcicolella 
Finally I realized that I've not connected to VPN which will allow me to connect to git url used in swagger-maven-plugin. Now, after connecting to VPN, I was able to build it with out any changes to the code.

I've committed the changes and created a pull-request
https://github.com/freedomotic/freedomotic/pull/377
