### ISSUE TITLE
Code gardening and Javadoc update of Freedomotic class 

### ISSUE THREAD

**Issue by mcicolella** [freedomotic/freedomotic#387]
Remove all issues reported by [Sonarcloud](https://sonarcloud.io/dashboard?id=com.freedomotic%3Afreedomotic-core%3Asrc%2Fmain%2Fjava%2Fcom%2Ffreedomotic%2Fapp%2FFreedomotic.java) and update/complete Javadoc.

PLEASE BE CAREFUL BEFORE SENDING A PR

1.Double check every issue with great attention. Sonarcloud sometimes reports 'false' issues (e.g. unused variables but they are really used). In case of doubt ask our team
2.For Javadoc please follow the official style guide conventions http://www.oracle.com/technetwork/java/javase/documentation/index-137868.html
3.Review texts and fix typos and/or grammatical errors
4.Compile the code
5.Run the code to be sure there aren't runtime exceptions
6.If you want to propose a better implementation please add a comment describing your proposal of refactoring
7.Please REBASE your working branch and SUBMIT a single commit PR
Notes:
**1. Don't remove TODO lines and DEPRECATED methods
2. Substitute RuntimeException with FreedomoticRuntimeException**

**Comment by h93xV2** [comment]
I would like to work on this

**Comment by yirrilo** [comment]
Hi @h93xV2, hi @mcicolella,
If the work did not begin, I can handle this issue tomorrow. Let me know !
Best regards
Yann

**Comment by mcicolella** [comment]
@yirrilo I don't know if @h93xV2 is working on this. No update.

**Comment by h93xV2** [comment]
@yirrilo Feel free to take over on this. I don't have time to get this done
