### ISSUE TITLE
Update Atmosphere library to the last version

### ISSUE THREAD

**Issue by mcicolella** [freedomotic/freedomotic#411]
For our [RestAPI](https://github.com/freedomotic/freedomotic/tree/master/plugins/devices/restapi-v3) plugin we are using [Atmosphere](https://github.com/Atmosphere/atmosphere) framework.
Currently it uses 2.2.5 version but the last available is 2.4.14.
We should update the code.

**Comment by pgrosslicht** [comment]
I can do that.

**Comment by mcicolella** [comment]
@pgrosslicht are you working on this?

**Comment by dmitraver** [comment]
I can pick this up
