### ISSUE TITLE
Make Freedomotic compatible with Java 11

### ISSUE THREAD

**Issue by mcicolella** [freedomotic/freedomotic#445]
Freedomotic is running on JDK 8. We should check if it's compliant with 10 version.

**Comment by aumarbello** [comment]
Hello, would like to pick this issue up.

Which version should it be tested agaist? 9 or 10?

**Comment by dmitraver** [comment]
I had problems building the project having java 10. Can run it again and post error messages here.

**Comment by mcicolella** [comment]
@aumarbello java 10
@dmitraver yes, thanks

**Comment by mcicolella** [comment]
@aumarbello for now we need to know if there are some problems with newer versions.

**Comment by aumarbello** [comment]
Okay, would run on Java 9 and 10 and report back any issues I experience.

**Comment by mcicolella** [comment]
@aumarbello thanks for your help.

**Comment by mcicolella** [comment]
Currently Java 11 is the default version.
Freedomotic is not compatible: the code doesn't compile on JDK 11 and the binary based on Java 8 doesn't run on 11.
We need to fix it ASAP.

**Comment by mcicolella** [comment]
The main problema is related to this code block
`
 URLClassLoader classLoader = (URLClassLoader) ClassLoader.getSystemClassLoader();
            Class<?> clazz = classLoader.loadClass(pojo.getHierarchy()); //eg: com.freedomotic.things.impl.ElectricDevice
            EnvObjectLogic logic = null;
            try {
                logic = (EnvObjectLogic) clazz.newInstance();
                logic.setPojo(pojo);
                injector.injectMembers(logic);
            } catch (InstantiationException ex) {
                LOG.error(Freedomotic.getStackTraceInfo(ex));
            } catch (IllegalAccessException ex) {
                LOG.error(Freedomotic.getStackTraceInfo(ex));
            }
`
[here](https://github.com/freedomotic/freedomotic/blob/47e3b427b55ecbec6d688933f8b3e8b99fe5c6a2/framework/freedomotic-core/src/main/java/com/freedomotic/things/ThingFactory.java#L60)

`URLClassLoader` is no more available in Java 11

**Comment by gmolica** [comment]
I will try to make it compatible with Java 11.

**Comment by mcicolella** [comment]
Thanks @gmolica

**Comment by mcicolella** [comment]
Fixed in 
90eaa5749052e8b14d03340b155577537adb244e  
b1221af6d14a5178710100346a0e48002bc49287
521acc345ec4665c3eaf71a7b558e9f1987ca0a9
