### ISSUE TITLE
Add icons with transparent background to Mailer plugin

### ISSUE THREAD

**Issue by mcicolella** [freedomotic/freedomotic#447]
We need to have the following icons with a transparent background or similar icons (same dimensions, resolution and subject) 
https://github.com/freedomotic/freedomotic/blob/master/plugins/devices/mailer/src/main/resources/data/resources/mailer-running.png
https://github.com/freedomotic/freedomotic/blob/master/plugins/devices/mailer/src/main/resources/data/resources/mailer-stopped.png

**Comment by hariprasanths** [comment]
can i work on this?

**Comment by mcicolella** [comment]
@hariprasanths yes

**Comment by zedd-08** [comment]
Can I work on this?

**Comment by mcicolella** [comment]
Fixed in 5d2a60269636544fa4f4f645f529fa6fb3c28801
