### ISSUE TITLE
Add icons with transparent background to Scheduler plugin 

### ISSUE THREAD

**Issue by mcicolella** [freedomotic/freedomotic#448]
We need to have the following icons with a transparent background or similar icons (same dimensions, resolution and subject)

https://github.com/freedomotic/freedomotic/blob/master/plugins/devices/essential/src/main/resources/data/resources/scheduler-running.png
https://github.com/freedomotic/freedomotic/blob/master/plugins/devices/essential/src/main/resources/data/resources/scheduler-stopped.png

**Comment by AlexMenor** [comment]
i could work on this

**Comment by mcicolella** [comment]
Fixed in 512d1998226f5b3f5c720f0e9152d10b0bbddd03
