### ISSUE TITLE
Add ObjectHasChanged event

### ISSUE THREAD

**Issue by mcicolella** [freedomotic/freedomotic#456]
This event can be useful to send a notification when a new thing is added or removed or has changed its properties.

Rif.[ Events](https://github.com/freedomotic/freedomotic/tree/master/framework/freedomotic-core/src/main/java/com/freedomotic/events)

**Comment by sebast26** [comment]
@mcicolella I can work on that. Could you please provide more details on what exactly should be added inside this event?

**Comment by mcicolella** [comment]
@sebast26 in few words we should create an event similar to [TriggerHasChanged](https://github.com/freedomotic/freedomotic/blob/master/framework/freedomotic-core/src/main/java/com/freedomotic/events/TriggerHasChanged.java) where 'trigger' is replaced by 'object' everywhere.
